services:
  keycloak-server:
    image: quay.io/keycloak/keycloak:latest
    container_name: track-hive-keycloak-server
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/9000 && printf 'GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && cat <&3 | grep UP"]
      start_period: 60s
      interval: 30s
      retries: 5
      timeout: 10s
    volumes:
      - ./keycloak/theme:/opt/keycloak/themes/modern
  minio-object-storage:
    image: minio/minio:latest
    container_name: track-hive-minio-storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://minio-object-storage:9000/minio/health/live"]
      start_period: 30s
      retries: 3
      timeout: 10s
  mysql-database:
    image: mysql:latest
    container_name: track-hive-mysql-db
    volumes:
      - ./mysql/init.sh:/docker-entrypoint-initdb.d/init.sh  # database init script
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute='SHOW DATABASES;'"]
      start_period: 30s
      retries: 3
      timeout: 10s
  mongo-database:
    image: mongo:latest
    container_name: track-hive-mongo-db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "mongosh admin -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet --eval 'db.serverStatus()'" ]
      start_period: 30s
      retries: 3
      timeout: 10s
  redis-database:
    image: redis:latest
    container_name: track-hive-redis-db
    restart: unless-stopped 
    # command: redis-server --requirepass $REDIS_PASSWORD                     # does not expand env variable
    command: ["sh", "-c", "redis-server --requirepass $$REDIS_PASSWORD"]
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping" ]
      start_period: 30s
      retries: 3
      timeout: 10s
  # track-hive-backend:
  #   build: .
  #   container_name: track-hive-backend
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     MINIO_ENDPOINT: minio-object-storage:9000
  #     MINIO_ACCESS_KEY: minioadmin
  #     MINIO_SECRET_KEY: minioadmin
  #     MYSQL_HOST: mysql-database
  #     MYSQL_PORT: 3306
  #     MYSQL_DATABASE: mydatabase
  #     MYSQL_USER: myuser
  #     MYSQL_PASSWORD: mypassword
  #     MONGO_HOST: mongodb-database
  #     MONGO_PORT: 27017
  #     MONGO_INITDB_ROOT_USERNAME: mongoadmin
  #     MONGO_INITDB_ROOT_PASSWORD: mongopassword
  #     REDIS_HOST: redis-database
  #     REDIS_PORT: 6379
  #   track-hive-backend:
  #     depends_on:
  #       - minio-object-storage
  #       - mysql-database
  #       - mongodb-database
  #       - redis-database
  
networks:
  default:                                              # override default network created by docker-compose
    name: track-hive-network