spring.application.name=track.hive.backend

# SQL DATABASE CONNECTION
mysql.connection.string=jdbc:mysql://${TRACK_HIVE_SQL_DB_SERVER_HOSTNAME}:${TRACK_HIVE_SQL_DB_SERVER_PORT}/${TRACK_HIVE_SQL_DB_NAME}
mysql.connection.properties=connectTimeout=5000&socketTimeout=30000&autoReconnect=true&useSSL=true&requireSSL=true
spring.datasource.url=${mysql.connection.string}?${mysql.connection.properties}
spring.datasource.username=${TRACK_HIVE_SQL_DB_USERNAME}
spring.datasource.password=${TRACK_HIVE_SQL_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2     
spring.datasource.hikari.connection-timeout=30000   
spring.datasource.hikari.idle-timeout=600000    

spring.jpa.show-sql=true    
spring.jpa.hibernate.ddl-auto=update    
spring.jpa.properties.hibernate.generate_statistics=true

logging.level.org.hibernate.stat=DEBUG        
