spring.application.name=track.hive.backend

# SQL DATABASE CONNECTION PROPERTIES
# auto reconnect, use SSL, require SSL from the database server, set TCP connection and socket timeouts
spring.datasource.url=jdbc:mysql://${TRACK_HIVE_SQL_DB_SERVER_HOSTNAME}:${TRACK_HIVE_SQL_DB_SERVER_PORT}/${TRACK_HIVE_SQL_DB_NAME}?connectTimeout=5000&socketTimeout=30000&autoReconnect=true&useSSL=true&requireSSL=true
spring.datasource.username=${TRACK_HIVE_SQL_DB_USERNAME}
spring.datasource.password=${TRACK_HIVE_SQL_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# size of the connection pool
spring.datasource.hikari.maximum-pool-size=10
# number of connections that are kept open and ready to use, even if they are not currently being used
spring.datasource.hikari.minimum-idle=2
# connection timeout in milliseconds
spring.datasource.hikari.connection-timeout=30000
# maximum time that a connection is allowed to sit idle in the pool
spring.datasource.hikari.idle-timeout=600000
# show sql command outputs
spring.jpa.show-sql=true
# automatically update database schema based on entity definitions, without dropping existing data
spring.jpa.hibernate.ddl-auto=update    
# Log slow queries
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG        
