#!/bin/sh
set -e

mysql --user=root --password="$MYSQL_ROOT_PASSWORD" <<-SQL
    CREATE USER IF NOT EXISTS '$TRACK_HIVE_BACKEND_USER'@'%' IDENTIFIED BY '$TRACK_HIVE_BACKEND_PASSWORD';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES ON \`$MYSQL_DATABASE\`.* TO '$TRACK_HIVE_BACKEND_USER'@'%';
    FLUSH PRIVILEGES;
SQL
